/**
 * STYLE REMINDER — Terminal Ledger guide index: editorial note cards, calm reading density,
 * lime metadata, and no performative outcome promises or generic content-farm structure.
 */

import { ArrowUpRight, Search } from "lucide-react";
import { Link } from "wouter";
import { Eyebrow } from "@/components/PageElements";
import { articleRegistry } from "@/lib/siteData";

export function BlogIndex() {
  return <><section className="border-b border-white/10 px-4 pb-16 pt-16 sm:px-8 sm:pb-24 sm:pt-24"><div className="mx-auto max-w-[1440px]"><Eyebrow>SmartStaker guide desk</Eyebrow><div className="mt-7 grid gap-8 lg:grid-cols-[1.25fr_0.75fr] lg:items-end"><h1 className="font-display text-[clamp(4rem,8vw,8rem)] leading-[0.83] tracking-[-0.06em] text-[#f1f0e9]">Read the limit<br />before <em className="font-normal text-[#a8ff58]">the interface.</em></h1><p className="max-w-lg text-base leading-8 text-[#a9afa8]">A responsible, design-led library on session framing, risk language, records, and why a polished workflow does not alter chance.</p></div><div className="mt-14 flex items-center gap-3 border-y border-white/10 py-4 font-mono text-[10px] uppercase tracking-[0.13em] text-[#8d948b]"><Search className="h-4 w-4 text-[#a8ff58]" />Search is represented as a static index in this preview.</div></div></section><section className="px-4 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-[1440px]"><div className="grid gap-x-10 gap-y-0 border-t border-white/20 lg:grid-cols-2">{articleRegistry.map((article, index) => <Link key={article.slug} href={`/blog/${article.slug}`} className="group border-b border-white/15 py-9"><div className="flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.13em] text-[#a8ff58]"><span>{String(index + 1).padStart(2, "0")} / {article.category}</span><span className="text-[#8d948b]">{article.minutes}</span></div><h2 className="mt-8 max-w-xl font-display text-4xl leading-[0.98] text-[#f1f0e9] transition-colors group-hover:text-[#a8ff58]">{article.title}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#a9afa8]">{article.description}</p><span className="mt-7 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.13em] text-[#d6dad2]">Read guide <ArrowUpRight className="h-3.5 w-3.5" /></span></Link>)}</div></div></section></>;
}

export function ArticlePage({ slug }: { slug: string }) {
  const article = articleRegistry.find((item) => item.slug === slug) ?? { category: "Guide archive", title: "A note from the SmartStaker guide desk.", description: "This reference-style article route is available as a responsive editorial template.", minutes: "6 min" };
  return <><section className="border-b border-white/10 px-4 pb-16 pt-12 sm:px-8 sm:pb-24 sm:pt-20"><div className="mx-auto max-w-4xl"><Link href="/blog" className="font-mono text-[10px] uppercase tracking-[0.13em] text-[#a9afa8] hover:text-[#a8ff58]">← Back to guide desk</Link><p className="mt-16 font-mono text-[10px] uppercase tracking-[0.15em] text-[#a8ff58]">{article.category} · {article.minutes}</p><h1 className="mt-6 font-display text-[clamp(3.8rem,7vw,7rem)] leading-[0.86] tracking-[-0.06em] text-[#f1f0e9]">{article.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#adb3aa]">{article.description}</p></div></section><article className="px-4 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-4xl gap-12 lg:grid-cols-[0.25fr_0.75fr]"><aside className="font-mono text-[10px] uppercase tracking-[0.13em] text-[#8c9389]"><span className="text-[#a8ff58]">Contents</span><p className="mt-4 leading-7">01 / The premise<br />02 / The boundary<br />03 / The practical reading</p></aside><div className="prose-signal"><p>Interface quality can make a workflow easier to see, but it cannot turn uncertainty into certainty. A useful product view begins by naming its limits: what a control can change, what it cannot change, and where a person remains responsible for the decision.</p><h2>Start with the boundary.</h2><p>The most important design move is often not another control. It is the sentence that sits beside the control: a session limit, a statement of uncertainty, a reminder that a record is not a prediction, or a clear distinction between a visual preview and a live action.</p><blockquote>“A well-framed record is evidence of what happened, not a guarantee of what happens next.”</blockquote><h2>Keep the decision visible.</h2><p>When pace, exit conditions, and risk are visible together, an interface can encourage a more deliberate reading of the session. That is the role of this guide library: to describe the context around a workflow without claiming a system can eliminate variance or produce a financial outcome.</p><h2>Use the result as a record.</h2><p>Short runs are noisy. A calm, consistent record can help people understand the difference between a configured plan and an observed outcome. It should never be used to turn chance into a marketing claim.</p></div></div></article><section className="border-y border-white/10 bg-[#111412] px-4 py-10 sm:px-8"><div className="mx-auto flex max-w-4xl items-center justify-between gap-5"><p className="font-display text-2xl text-[#f1f0e9]">Continue through the guide desk.</p><Link href="/blog" className="font-mono text-[10px] uppercase tracking-[0.12em] text-[#a8ff58]">All guides →</Link></div></section></>;
}
