/**
 * STYLE REMINDER — Reference-faithful blog: grid-field intro, conversion bar, readable article rhythm,
 * teal micro-labels, large serif headlines, and long-form content without dashboard density.
 */

import { ArrowLeft, ArrowRight, Download } from "lucide-react";
import { Link } from "wouter";
import { articleRegistry, getArticle } from "@/lib/siteData";

export function BlogIndex() { return <><section className="page-grid border-b border-white/[0.08] px-5 pb-14 pt-16 sm:pt-20"><div className="mx-auto max-w-[1120px]"><p className="eyebrow">Blog</p><h1 className="mt-5 font-display text-[clamp(3.5rem,7vw,6rem)] leading-[0.92] tracking-[-0.05em] text-[#eef0ed]">SmartStaker <em className="font-normal text-[#55c4ab]">Guides</em> & Strategies</h1><p className="mt-6 max-w-2xl text-[15px] leading-7 text-[#a7b0ac]">Product notes, configuration guides, session-review patterns, and deep dives for more structured platform workflows.</p><div className="mt-9 flex flex-col justify-between gap-4 border border-white/[0.1] bg-[#161a1c] p-5 sm:flex-row sm:items-center"><div><p className="font-display text-xl text-[#e6ebe7]">Ready to explore the desktop workflow?</p><p className="mt-1 text-sm text-[#909a96]">Review the platform and supported product surfaces.</p></div><Link href="/download" className="inline-flex w-fit items-center gap-2 bg-[linear-gradient(105deg,#49c4aa,#89d96c)] px-5 py-3 text-sm font-semibold text-[#0b1715]"><Download className="h-4 w-4" />Download SmartStaker</Link></div></div></section><section className="px-5 py-16 sm:py-20"><div className="mx-auto max-w-[940px] divide-y divide-white/[0.1] border-y border-white/[0.1]">{articleRegistry.map((article) => <Link key={article.slug} href={`/blog/${article.slug}`} className="group grid gap-4 py-8 sm:grid-cols-[120px_1fr_auto] sm:items-start"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#58c7ae]">{article.category}</p><div><h2 className="font-display text-3xl leading-[1.05] text-[#edf0ed] transition-colors group-hover:text-[#65d0b8] sm:text-4xl">{article.title}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#98a29e]">{article.description}</p><p className="mt-4 font-mono text-[10px] uppercase tracking-[0.12em] text-[#68746f]">{article.date} · {article.reading}</p></div><ArrowRight className="h-5 w-5 text-[#56c6ae] transition-transform group-hover:translate-x-1" /></Link>)}</div></section></>; }

export function ArticlePage({ slug }: { slug: string }) { const article = getArticle(slug); return <><section className="page-grid border-b border-white/[0.08] px-5 pb-14 pt-14"><div className="mx-auto max-w-[860px]"><Link href="/blog" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.13em] text-[#67ceb8] hover:text-[#9be1d0]"><ArrowLeft className="h-3.5 w-3.5" />All guides</Link><p className="mt-12 eyebrow">{article.category}</p><h1 className="mt-5 font-display text-[clamp(3rem,6vw,5.4rem)] leading-[0.94] tracking-[-0.05em] text-[#edf0ed]">{article.title}</h1><p className="mt-6 max-w-2xl text-[15px] leading-8 text-[#a6afab]">{article.description}</p><p className="mt-7 font-mono text-[10px] uppercase tracking-[0.13em] text-[#6f7c77]">{article.date} · {article.reading}</p></div></section><article className="px-5 py-16 sm:py-20"><div className="article-prose mx-auto max-w-[760px]"><p>SmartStaker guides are written to make a configuration easier to understand before it becomes part of a session. The relevant variables, limits, and workflow conditions deserve the same attention as any headline result.</p><h2>Start with the structure</h2><p>Document the objective, selected controls, boundaries, and review point in the same place. A clear structure does not change random outcomes; it makes it easier to see what the plan actually is and when the plan should end.</p><h2>Keep variance in the frame</h2><p>Short sequences are not a reliable basis for a prediction. Use a session record to review the behavior of a setup, not to infer certainty from a run of results. Any activity that involves a financial stake should have a pre-defined limit.</p><blockquote>“A workflow is useful when its controls and stopping points are still clear after the session is underway.”</blockquote><h2>Review what can be measured</h2><p>Duration, volume, stop conditions, and the history of configuration changes can be more useful than a headline number alone. When reviewing, look for whether the setup was followed and whether the relevant limits remained visible.</p><h2>Use the guide as a starting point</h2><p>SmartStaker provides a product-information architecture, not financial, investment, or gambling advice. Assess local rules, platform terms, and personal risk before deciding whether to use any third-party tool.</p></div></article><section className="border-y border-white/[0.08] bg-[#15191b] px-5 py-14"><div className="mx-auto flex max-w-[860px] flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="eyebrow">Continue reading</p><p className="mt-3 font-display text-3xl text-[#edf0ed]">More guides from <em className="font-normal text-[#55c4ab]">SmartStaker.</em></p></div><Link href="/blog" className="inline-flex items-center gap-2 text-sm text-[#68cfb9]">View all articles <ArrowRight className="h-4 w-4" /></Link></div></section></>; }
