/**
 * STYLE REMINDER — Reference-faithful legal routes: grid-field hero, legal badge, updated date,
 * one dark bordered article slab, serif clause headings, and restrained policy typography.
 */

const privacy = [["1. Introduction", "SmartStaker respects user privacy and aims to explain how this public website and any future desktop application may handle information. This page is a product-site policy draft and should be reviewed against the final released application."], ["2. Information We Collect", "Website analytics may include pages visited, browser type, device information, approximate location, and interaction events. A desktop application should clearly state which information remains local and which information is transmitted before a user connects any account."], ["3. How We Use Information", "Limited website information may be used to understand site performance, improve content, diagnose errors, and assess which product pages are useful. SmartStaker does not sell personal information through this static site."], ["4. Cookies", "This site may use analytics and preference cookies. You can control cookies through browser settings, although disabling them may affect some website preferences."], ["5. Data Security", "Reasonable security measures should be applied to any data processed by the released product. Users should keep credentials private and review the final application documentation before connecting a platform account."], ["6. Children’s Privacy", "SmartStaker is not intended for people under the age of 18 or the legal gambling age in their jurisdiction, whichever is higher."], ["7. Changes to This Policy", "This policy may change as the product and its data practices are finalized. The revision date will be updated when material changes are published."]];
const terms = [["1. Acceptance of Terms", "By accessing the SmartStaker website or using a future SmartStaker desktop application, you agree to these terms. If you do not agree, do not use the site or product."], ["2. Description of Service", "SmartStaker is presented as an independent desktop companion for configurable platform workflows, reporting, and notification utilities. Features described on this site may change before release."], ["3. Eligibility", "You must be at least 18 years old, or the legal gambling age in your jurisdiction if higher, to use a product associated with gambling-related platforms."], ["4. No Affiliation", "SmartStaker is an independent third-party product and is not affiliated with, endorsed by, or officially connected to any external gaming platform. Product and company names belong to their respective owners."], ["5. User Responsibilities", "You are responsible for complying with all applicable law, platform terms, and account requirements. Gambling carries risk. Never use funds you cannot afford to lose, and do not assume a workflow or strategy can guarantee a result."], ["6. No Financial Advice", "Nothing on this website constitutes financial, investment, or gambling advice. Guides and product information are for educational and informational purposes only."], ["7. Account Risks", "Third-party automation or companion tools may conflict with platform terms and can result in account restrictions. You use any released product at your own risk."], ["8. Changes and Termination", "SmartStaker may modify product information, terms, or availability at any time. Continued use following a published revision indicates acceptance of the revised terms."]];

export function LegalPage({ type }: { type: "privacy" | "terms" }) { const isPrivacy = type === "privacy"; const sections = isPrivacy ? privacy : terms; return <><section className="page-grid border-b border-white/[0.08] px-5 pb-12 pt-16"><div className="mx-auto max-w-[1120px]"><p className="eyebrow">Legal</p><h1 className="mt-5 font-display text-[clamp(3.5rem,7vw,6rem)] leading-[0.92] text-[#edf0ed]">{isPrivacy ? <>Privacy <em className="font-normal text-[#55c4ab]">Policy</em></> : <>Terms of <em className="font-normal text-[#55c4ab]">Service</em></>}</h1><p className="mt-5 text-sm text-[#8e9995]">Last updated: August 15, 2026</p></div></section><section className="px-5 py-16 sm:py-20"><article className="mx-auto max-w-[1120px] border border-[#2b3434] bg-[#161a1c] p-7 sm:p-10">{sections.map(([heading, copy]) => <section key={heading} className="border-b border-white/[0.08] py-8 first:pt-0 last:border-b-0 last:pb-0"><h2 className="font-display text-3xl text-[#edf0ed]">{heading}</h2><p className="mt-4 max-w-3xl text-[15px] leading-8 text-[#a1aaa6]">{copy}</p></section>)}</article></section></>; }
