/**
 * STYLE REMINDER — Reference-faithful product routes: left-aligned grid hero, teal-accented display title,
 * long explanatory blocks, settings surface, feature grid, workflow guide, FAQ, related links, final CTA.
 */

import { ArrowRight, Check, Download, Settings2 } from "lucide-react";
import { Link } from "wouter";
import { getProductPage } from "@/lib/siteData";

export default function ProductPage({ slug }: { slug: string }) {
  const page = getProductPage(slug);
  if (!page) return <section className="page-grid px-5 py-32"><div className="mx-auto max-w-[1120px]"><p className="eyebrow">404</p><h1 className="mt-5 font-display text-6xl text-[#eef1ed]">Page not found.</h1><Link href="/" className="mt-8 inline-flex text-[#62cdb6]">Return home →</Link></div></section>;
  const game = page.kind === "game";
  return <>
    <section className="page-grid border-b border-white/[0.08] px-5 pb-16 pt-16 sm:pb-20 sm:pt-20"><div className="mx-auto max-w-[1120px]"><div className="max-w-4xl"><div className="inline-flex items-center gap-3"><span className="grid h-11 w-11 place-items-center border border-[#4ec1a7]/50 text-[#63d0b8]"><Settings2 className="h-4 w-4" /></span><span className="eyebrow">{page.badge}</span></div><h1 className="mt-8 max-w-4xl font-display text-[clamp(3.35rem,7vw,6.5rem)] leading-[0.9] tracking-[-0.055em] text-[#eef0ed]">{page.title} <em className="font-normal text-[#53c2aa]">{page.accent}</em></h1><p className="mt-7 max-w-3xl text-[15px] leading-8 text-[#a5aeaa] sm:text-lg">{page.description}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/download" className="inline-flex items-center gap-2 bg-[linear-gradient(105deg,#49c4aa,#89d96c)] px-5 py-3 text-sm font-semibold text-[#0a1714] transition-transform hover:-translate-y-0.5"><Download className="h-4 w-4" />Download SmartStaker</Link><a href="#features" className="inline-flex items-center gap-2 border border-[#3e897a] px-5 py-3 text-sm font-medium text-[#62cfb6] hover:bg-[#173a33]">View all features <ArrowRight className="h-4 w-4" /></a></div></div></div></section>
    <section className="px-5 py-20 sm:py-24"><div className="mx-auto grid max-w-[1120px] gap-12 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="eyebrow">{page.introTitle}</p>{page.intro.map((paragraph) => <p key={paragraph} className="mt-5 text-[15px] leading-8 text-[#a7afab]">{paragraph}</p>)}</div><div className="border-l border-[#4abda5]/50 pl-6"><p className="font-display text-3xl text-[#e8ede9]">Why choose SmartStaker?</p><ul className="mt-6 grid gap-3">{page.benefits.map((benefit) => <li key={benefit} className="flex items-start gap-3 text-sm leading-6 text-[#b8c1bd]"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-[#62d2bb]" />{benefit}</li>)}</ul></div></div></section>
    {game && page.settings && <section className="border-y border-white/[0.08] bg-[#15191b] px-5 py-20"><div className="mx-auto max-w-[1120px]"><p className="eyebrow">{page.title} settings</p><h2 className="mt-4 font-display text-5xl text-[#edf0ed]">Set the workflow <em className="font-normal text-[#55c4ab]">before the session.</em></h2><div className="mt-10 grid overflow-hidden border border-white/[0.1] sm:grid-cols-2">{page.settings.map((setting, index) => <div key={setting.label} className={`flex items-center justify-between gap-4 border-white/[0.08] bg-[#111517] px-5 py-4 ${index % 2 === 0 ? "sm:border-r" : ""} border-b last:border-b-0`}><span className="text-sm text-[#a5afab]">{setting.label}</span><span className="font-mono text-[10px] uppercase tracking-[0.12em] text-[#62cfb6]">{setting.value}</span></div>)}</div></div></section>}
    <section id="features" className="px-5 py-20 sm:py-24"><div className="mx-auto max-w-[1120px]"><p className="eyebrow">SmartStaker features</p><h2 className="mt-4 max-w-2xl font-display text-5xl leading-[0.95] text-[#edf0ed]">A complete set of <em className="font-normal text-[#55c4ab]">workflows.</em></h2><div className="mt-10 grid gap-px border border-white/[0.08] bg-white/[0.08] md:grid-cols-2 lg:grid-cols-3">{page.features.map((feature, index) => <article key={feature.title} className="min-h-[190px] bg-[#131719] p-6"><span className="font-mono text-[10px] tracking-[0.13em] text-[#57c6ae]">0{index + 1}</span><h3 className="mt-7 font-display text-3xl text-[#edf0ed]">{feature.title}</h3><p className="mt-3 text-sm leading-6 text-[#929c98]">{feature.copy}</p></article>)}</div></div></section>
    <section className="border-y border-white/[0.08] bg-[#14181a] px-5 py-12"><div className="mx-auto flex max-w-[1120px] flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display text-3xl text-[#edf0ed]">Ready to explore the desktop workflow?</p><p className="mt-2 text-sm text-[#8e9995]">Review product availability and release notes for SmartStaker.</p></div><Link href="/download" className="inline-flex w-fit items-center gap-2 bg-[linear-gradient(105deg,#49c4aa,#89d96c)] px-5 py-3 text-sm font-semibold text-[#0b1715]"><Download className="h-4 w-4" />Download SmartStaker</Link></div></section>
    <section className="px-5 py-20 sm:py-24"><div className="mx-auto max-w-[1120px]"><p className="eyebrow">Step-by-step guide</p><h2 className="mt-4 font-display text-5xl text-[#edf0ed]">How to use the <em className="font-normal text-[#55c4ab]">workflow.</em></h2><div className="mt-10 grid gap-px border border-white/[0.08] bg-white/[0.08] md:grid-cols-4">{page.steps.map((step, index) => <article key={step.title} className="bg-[#121619] p-6"><span className="font-mono text-xs text-[#58c7ae]">0{index + 1}</span><h3 className="mt-12 font-display text-2xl text-[#ecf0ec]">{step.title}</h3><p className="mt-3 text-sm leading-6 text-[#929c99]">{step.copy}</p></article>)}</div></div></section>
    <section className="border-y border-white/[0.08] bg-[#15191b] px-5 py-20"><div className="mx-auto grid max-w-[1120px] gap-12 lg:grid-cols-[0.72fr_1.28fr]"><div><p className="eyebrow">Frequently asked</p><h2 className="mt-4 font-display text-5xl text-[#edf0ed]">{page.title} <em className="font-normal text-[#55c4ab]">FAQ.</em></h2></div><div className="divide-y divide-white/[0.1] border-y border-white/[0.1]">{page.faqs.map((item, index) => <details key={item.question} className="group py-4"><summary className="flex cursor-pointer list-none items-center gap-4 text-[15px] text-[#dce2de]"><span className="font-mono text-[10px] text-[#58c7ae]">0{index + 1}</span>{item.question}<span className="ml-auto text-[#61cbb4] group-open:rotate-45">+</span></summary><p className="pl-8 pt-3 text-sm leading-7 text-[#929d99]">{item.answer}</p></details>)}</div></div></section>
    <section className="px-5 py-20"><div className="mx-auto max-w-[1120px]"><p className="eyebrow">Explore more features</p><div className="mt-7 grid gap-px border border-white/[0.08] bg-white/[0.08] sm:grid-cols-2 lg:grid-cols-4">{page.related.map((item) => <Link key={item.href} href={item.href} className="flex min-h-24 items-end justify-between bg-[#131719] p-5 text-lg text-[#dfe5e1] transition-colors hover:bg-[#1a2222] hover:text-[#6bd3bb]">{item.label}<ArrowRight className="h-4 w-4" /></Link>)}</div></div></section>
    <section className="border-t border-white/[0.08] px-5 py-20 text-center"><div className="mx-auto max-w-2xl"><p className="eyebrow">SmartStaker desktop</p><h2 className="mt-5 font-display text-5xl text-[#eef1ed]">Start with a <em className="font-normal text-[#55c4ab]">clearer workflow.</em></h2><div className="mt-7 flex justify-center"><Link href="/download" className="inline-flex items-center gap-2 bg-[linear-gradient(105deg,#49c4aa,#89d96c)] px-5 py-3 text-sm font-semibold text-[#0b1715]"><Download className="h-4 w-4" />Download SmartStaker</Link></div></div></section>
  </>;
}
